//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsonCompareDevToy {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JsonCompareDevToy.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare tool for JSON files.
        /// </summary>
        internal static string AccessibleName {
            get {
                return ResourceManager.GetString("AccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrays on path {0} have unequal count of elements {1} vs {2}.
        /// </summary>
        internal static string ArraysOnPathHaveInequalCountOfElements {
            get {
                return ResourceManager.GetString("ArraysOnPathHaveInequalCountOfElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare tool for JSON files.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR:.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files are identical.
        /// </summary>
        internal static string FilesAreIdentical {
            get {
                return ResourceManager.GetString("FilesAreIdentical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON of the first file.
        /// </summary>
        internal static string JsonOfTheFirstFile {
            get {
                return ResourceManager.GetString("JsonOfTheFirstFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON of the second file.
        /// </summary>
        internal static string JsonOfTheSecondFile {
            get {
                return ResourceManager.GetString("JsonOfTheSecondFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON Compare.
        /// </summary>
        internal static string LongDisplayTitle {
            get {
                return ResourceManager.GetString("LongDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results.
        /// </summary>
        internal static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object on path {0} in first file {1} does not have property with name {2}.
        /// </summary>
        internal static string ObjectOnPathInFileDoesNotHavePropertyWithName {
            get {
                return ResourceManager.GetString("ObjectOnPathInFileDoesNotHavePropertyWithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object on path {0} in {1} file has duplicate property name {2}.
        /// </summary>
        internal static string ObjectOnPathInFileHasDuplicatePropertyName {
            get {
                return ResourceManager.GetString("ObjectOnPathInFileHasDuplicatePropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARSE ERROR of the first file:.
        /// </summary>
        internal static string ParseErrorOfTheFirstFile {
            get {
                return ResourceManager.GetString("ParseErrorOfTheFirstFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARSE ERROR of the second file:.
        /// </summary>
        internal static string ParseErrorOfTheSecondFile {
            get {
                return ResourceManager.GetString("ParseErrorOfTheSecondFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON Compare.
        /// </summary>
        internal static string ShortDisplayTitle {
            get {
                return ResourceManager.GetString("ShortDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use strict compare.
        /// </summary>
        internal static string UseStrictCompare {
            get {
                return ResourceManager.GetString("UseStrictCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values on path {0} are different types {1} vs {2}.
        /// </summary>
        internal static string ValuesOnPathAreDifferentTypes {
            get {
                return ResourceManager.GetString("ValuesOnPathAreDifferentTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values on path {0} are not equal {1} vs {2}.
        /// </summary>
        internal static string ValuesOnPathAreNotEqual {
            get {
                return ResourceManager.GetString("ValuesOnPathAreNotEqual", resourceCulture);
            }
        }
    }
}
